const Paths = {
  any: '*',
  admin: '/admin',
  user: '/user',
  root: '/',
  login: '/login',
  logout: '/logout',
  signup: '/signup',
  activation: '/account/activation',
  home: 'home',
  account: 'account',
  settings: 'settings',
  users: 'users',
  tasks: 'tasks',
  groups: 'groups',
  tags: 'tags',
  categories: 'categories',
  roles: 'roles',
  statistics: 'statistics',
  create: 'create',
  update: 'update',
  delete: 'delete',
  groupId: ':groupID',
  taskId: ':taskID',
} as const;

export { Paths };
