"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express_1 = require("express");
var userController = require("../controllers/users-controller");
var router = (0, express_1.Router)();
exports.router = router;
router.get("/", userController.getAllUsers);
router.post("/login", userController.login);
router.post("/signup", userController.signup);
